export const jobs = [
  {
    id: "00112233-4455-6677-8899-aabbccddeeff",
    location: "San Francisco, CA",
    role_name: "Software Engineer",
    company_name: "OpenAI",
    description: "Leading AI research and deployment company.",
    experience_level: "Senior",
    required_skills: ["Python", "Machine Learning", "Deep Learning", "NLP"],
    categories: ["AI", "Research"],
    link_to_website: "https://www.openai.com",
    link_to_job: "https://www.openai.com/careers/software-engineer",
  },
  {
    id: "11223344-5566-7788-99aa-bbccddeeff00",
    location: "New York, NY",
    role_name: "Product Manager",
    company_name: "Stripe",
    description:
      "Global technology company building economic infrastructure for the internet.",
    experience_level: "Mid",
    required_skills: ["Product Management", "Agile", "Fintech"],
    categories: ["Fintech", "Payments"],
    link_to_website: "https://www.stripe.com",
    link_to_job: "https://stripe.com/jobs/product-manager",
  },
  {
    id: "22334455-6677-8899-aabb-ccddeeff0011",
    location: "Remote",
    role_name: "Frontend Developer",
    company_name: "GitLab",
    description: "Open-source code collaboration platform.",
    experience_level: "Entry",
    required_skills: ["JavaScript", "Vue.js", "HTML", "CSS"],
    categories: ["DevOps", "Open Source"],
    link_to_website: "https://www.gitlab.com",
    link_to_job: "https://about.gitlab.com/jobs/frontend-developer",
  },
  {
    id: "33445566-7788-99aa-bbcc-ddeeff001122",
    location: "Austin, TX",
    role_name: "Data Scientist",
    company_name: "Indeed",
    description: "Global employment-related search engine for job listings.",
    experience_level: "Mid",
    required_skills: ["Python", "R", "SQL", "Data Analysis"],
    categories: ["HR Tech", "Analytics"],
    link_to_website: "https://www.indeed.com",
    link_to_job: "https://www.indeed.jobs/data-scientist",
  },
  {
    id: "44556677-8899-aabb-ccdd-eeff00112233",
    location: "Chicago, IL",
    role_name: "UX Designer",
    company_name: "Grubhub",
    description: "Online and mobile food-ordering and delivery marketplace.",
    experience_level: "Mid",
    required_skills: [
      "UX Design",
      "Wireframing",
      "Prototyping",
      "User Research",
    ],
    categories: ["E-commerce", "Food Tech"],
    link_to_website: "https://www.grubhub.com",
    link_to_job: "https://careers.grubhub.com/ux-designer",
  },
  {
    id: "55667788-99aa-bbcc-ddee-ff0011223344",
    location: "Seattle, WA",
    role_name: "Cloud Solutions Architect",
    company_name: "Amazon Web Services",
    description: "Comprehensive and broadly adopted cloud platform.",
    experience_level: "Senior",
    required_skills: ["Cloud Architecture", "AWS", "DevOps", "Networking"],
    categories: ["Cloud Computing", "Infrastructure"],
    link_to_website: "https://aws.amazon.com",
    link_to_job: "https://aws.amazon.com/careers/cloud-solutions-architect",
  },
  {
    id: "66778899-aabb-ccdd-eeff-001122334455",
    location: "Boston, MA",
    role_name: "Machine Learning Engineer",
    company_name: "HubSpot",
    description:
      "Developer and marketer of software products for inbound marketing and sales.",
    experience_level: "Mid",
    required_skills: [
      "Python",
      "TensorFlow",
      "Machine Learning",
      "Data Engineering",
    ],
    categories: ["SaaS", "Marketing Tech"],
    link_to_website: "https://www.hubspot.com",
    link_to_job: "https://www.hubspot.com/careers/machine-learning-engineer",
  },
  {
    id: "778899aa-bbcc-ddee-ff00-112233445566",
    location: "Los Angeles, CA",
    role_name: "Mobile App Developer",
    company_name: "Snap Inc.",
    description: "Camera and social media company.",
    experience_level: "Mid",
    required_skills: ["Swift", "Objective-C", "iOS Development", "UI/UX"],
    categories: ["Social Media", "Mobile"],
    link_to_website: "https://www.snap.com",
    link_to_job: "https://www.snap.com/en-US/jobs/mobile-app-developer",
  },
  {
    id: "8899aabb-ccdd-eeff-0011-223344556677",
    location: "Denver, CO",
    role_name: "Backend Developer",
    company_name: "Slack",
    description: "Business communication platform.",
    experience_level: "Mid",
    required_skills: [
      "Java",
      "Spring Boot",
      "Microservices",
      "API Development",
    ],
    categories: ["Communication", "SaaS"],
    link_to_website: "https://slack.com",
    link_to_job: "https://slack.com/careers/backend-developer",
  },
  {
    id: "99aabbcc-ddee-ff00-1122-334455667788",
    location: "Toronto, ON",
    role_name: "DevOps Engineer",
    company_name: "Shopify",
    description:
      "E-commerce platform for online stores and retail point-of-sale systems.",
    experience_level: "Senior",
    required_skills: ["Kubernetes", "Docker", "CI/CD", "AWS"],
    categories: ["E-commerce", "Cloud Infrastructure"],
    link_to_website: "https://www.shopify.com",
    link_to_job: "https://www.shopify.com/careers/devops-engineer",
  },
];

export type Job = (typeof jobs)[number];
