job_finding_task:
  description: >
    Analyze job listings to identify positions matching the user preferences below
    Only include listings posted within the past week
    User preferences: {user_preferences}
    Current date: {date}
  expected_output: >
    A JSON array of job listings, each containing:
      - location: City or region where the job is located
      - role_name: Title of the job role
      - company_name: Name of the hiring company. If it's a bunch of jobs from a website, use "Jobs from <website_name>" instead
      - description: Brief summary or description of the company
      - experience_level: Level of experience required (e.g., Entry, Mid, Senior) 
      - required_skills: A list of required skills
      - categories: A list of industries or sectors related to the job (e.g., Enterprise Software, Fintech, Health Tech, Education Tech, E-commerce)
      - link_to_website: Direct link to the company's website
      - link_to_job: Direct link to the job posting
      - salary_range: The compensation range offered for the position, typically expressed in annual terms (e.g., $120,000 - $160,000)
      - work_arrangement: The working setup for the role, specifying whether it’s Onsite (at the company’s location), Hybrid (a mix of remote and onsite), or Remote (work from anywhere)
      - visa_sponsorship: Specifies whether the employer is willing to assist candidates who require legal authorization to work in the country (e.g., H-1B, O-1)
  agent: job_finder

resume_reading_task:
  description: >
    Access the user’s resume located at {filepath_to_resume} and analyze it to extract key details.
  expected_output: >
    A JSON object with the extracted information, including:
      - Contact information
      - Professional summary
      - Education
      -	Skills
      - Work experience
      - Projects
  agent: resume_reader

job_matching_task:
  description: >
    Compare the extracted resume details with the identified job listings to assess compatibility based on:
      - Alignment of required and possessed skills
      - Correspondence between job responsibilities and past experiences
      - Suitability of experience level
      - Relevance of educational background
  expected_output: >
    A JSON array of matched job listings, each including:
      - job_listing: Original job listing details including "location", "role_name", "company_name", "description", "experience_level", "required_skills", "categories", "link_to_website", "link_to_job", "salary_range", "work_arrangement", and "visa_sponsorship"
      - match_score: Numerical score (0-100) indicating the degree of match.
      - match_criteria: Explanation of how the candidate’s profile aligns with the job requirements.
  agent: matcher

job_quality_control_task:
  description: >
    Review the matched job listings to ensure they meet quality standards by verifying:
      - Accuracy of job details
      - Relevance to user preferences
      - Absence of duplicates
      - Validity of links: this is VERY IMPORTANT
  expected_output: >
    A JSON array of validated job listings, each containing:
      - job_listing: Original job listing details
      - validation_status: Boolean indicating if the listing passed quality checks
      - validation_notes: Comments on any issues or confirmations of quality
  agent: quality_control_specialist
  output_file: jobs.md
